// Generated by CoffeeScript 1.10.0
(function() {
  Array.prototype.average = function() {
    var i, len, sum, value;
    sum = 0;
    for (i = 0, len = this.length; i < len; i++) {
      value = this[i];
      sum += parseFloat(value);
    }
    return sum / this.length;
  };

  Array.prototype.variance = function() {
    var avg, value, variances;
    avg = this.average();
    variances = (function() {
      var i, len, results;
      results = [];
      for (i = 0, len = this.length; i < len; i++) {
        value = this[i];
        results.push(Math.pow(parseFloat(value) - avg, 2));
      }
      return results;
    }).call(this);
    return variances.average();
  };

  Array.prototype.standardDeviation = function() {
    return Math.sqrt(this.variance());
  };

}).call(this);
