// Generated by CoffeeScript 1.9.2
(function() {
  Array.prototype.average = function() {
    var i, len, sum, value;
    sum = 0;
    for (i = 0, len = this.length; i < len; i++) {
      value = this[i];
      sum += parseFloat(value);
    }
    return sum / this.length;
  };

}).call(this);
