// Generated by CoffeeScript 1.10.0
(function() {
  Number.isInteger = Number.isInteger || function(value) {
    return typeof value === "number" && isFinite(value) && Math.floor(value) === value;
  };

}).call(this);
