// Generated by CoffeeScript 1.9.2
(function() {
  String.prototype.capitalize = function() {
    return this.charAt(0).toUpperCase() + this.slice(1).toLowerCase();
  };

  String.prototype.toCamelCase = function() {
    var words;
    words = this.toLowerCase().split(/[-_]/);
    return words[0] + words.slice(1).map(function(text) {
      return text.capitalize();
    }).join('');
  };

  String.prototype.toUnderScore = function() {
    return this.replace(/[A-Z]/g, function(letter, index) {
      if (index === 0) {
        return letter.toLowerCase();
      } else {
        return '_' + letter.toLowerCase();
      }
    });
  };

}).call(this);

//# sourceMappingURL=String.js.map
